// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysFin.Data.BD;

namespace SysFin.Migrations
{
    [DbContext(typeof(SysFinDataContext))]
    [Migration("20200229002857_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SysFin.Domain.Entities.Fatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataChegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 2, 28, 20, 28, 55, 412, DateTimeKind.Local).AddTicks(4573));

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MesReferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2020, 2, 28, 20, 28, 55, 433, DateTimeKind.Local).AddTicks(358));

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PrestadorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("SysFin.Domain.Entities.PrestadorDeServico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("PrestadoresDeServico");

                    b.HasData(
                        new
                        {
                            Id = "67AA1C8DA3B74D048599",
                            Descricao = "Prestador de servico",
                            Nome = "Energisa"
                        });
                });

            modelBuilder.Entity("SysFin.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("SysFin.Domain.Entities.PrestadorDeServico", "Prestador")
                        .WithMany("Faturas")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
